### ISSUE TITLE
feature request: click to discard

### ISSUE THREAD

**Issue by derlin** [egoist/native-toast#6]
Thank you for this nice library.

It does exactly what is needed, except one thing: the ability to discard the toast on click. Would it be possible to add a simple option like:

     'disable-on-click': true

**Comment by rajraj** [comment]
@derlin This option is added now. https://github.com/egoist/native-toast#closeonclick

```js
nativeToast({
  message: 'wait wait!',
  closeOnClick: true
})
```

**Comment by egoist** [comment]
Closed as it's solved
